### ISSUE TITLE
Examples for <video>

### ISSUE THREAD

**Issue by aastrong** [NikxDa/ambient#1]
Can you give an example of what a video tag would look like. 
I can't seem to get it working. 

Images are working fine

**Comment by NikxDa** [comment]
Hey @aastrong,

you can find a working demo here: https://codepen.io/NikxDa/pen/gOQvqoP
Can you let me know what's not working for you?

Cheers

**Comment by NikxDa** [comment]
Closing this for now. If you have any problems with the demo, feel free to open another issue. 🙂

**Comment by aastrong** [comment]
Yup thx for the demo, seems to work fine. 
Must be something locally blocking mine.
